# config.yaml

data:
  raw_data_path: "dataset.csv"
  processed_data_path: "data/processed.csv"

preprocessing:
  test_size: 0.2
  random_state: 42
  categorical_encoding: "onehot"

model:
  type: "RandomForestClassifier"
  parameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42

output:
  metrics_path: "results/metrics.json"
  model_path: "results/churn_model.pkl"
